version: 2

sphinx:
    configuration: doc/conf.py

build:
    os: ubuntu-20.04
    tools:
        python: "3.8"
    jobs:
        post_install:
        # Not ideal, since PDM and project dependencies aren't isolated.
        - pip install --upgrade pdm
        # See https://github.com/pdm-project/pdm/discussions/1365
        - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm install -dG doc
